### ISSUE TITLE
Mutual usage of --channel-repo and -provision-config parameters

### ISSUE THREAD

**Issue by marekkopecky** [wildfly-extras/prospero#100]
Prospero allows to use --channel-repo and -provision-config together, but can't work with both of them

**Comment by TomasHofman** [comment]
I'm going to take a look.

**Comment by TomasHofman** [comment]
When using `--provision-config`, the `--remote-repositories` are indeed ignored. So either they should be taken into account as well, or this should be somehow documented in the usage message.

I would personally expect the `--remote-repositories` to be functional always. It might be also surprising that `--remote-repositories` overrides repositories predefined in the named feature pack definitions. Maybe we could have `--remote-repositories` that would be additive and `--override-remote-repositories` that would override?

WDYT @spyrkob?

**Comment by spyrkob** [comment]
@TomasHofman do you have a use case in mind where specifying both `--provision-config` and `--remote-repositories` would be useful?

In my mind, user should use either `provisioning-config.yaml` or command line parameters, not mix the two. The config file already lets user specify repositories, so adding/changing them via command line seems unnecessary and potentially a bit confusing.

We could use the picocli exclusive argument group for those two, I think that would fix both the help content and show error if user attempts to use both arguments.

> Maybe we could have --remote-repositories that would be additive and --override-remote-repositories that would override?
I feel like we already have too many command line options :) My thinking was that using `--remote-repositories` and `--channel` should be equivalent to a `provisioning-config.yaml` with the same values.
