### ISSUE TITLE
Cannot use Prospero CLI tool to update a server provisioning with Prospero feature packs

### ISSUE THREAD

**Issue by yersan** [wildfly-extras/prospero#172]
Hi, I'm using the wildfly-maven-plugin to provision a server with the Prospero feature paks, either standalone or local WildFly SNAPSHOT. When I try to update it I get the following error:

```
./bin/prospero.sh update
ERROR: Path `/Users/yborgess/dev/projects/wildfly-prospero/provisioning/target/server/.` does not contain a server installation provisioned by prospero.
```

I could be doing something wrong, but I would expect to have the ability to update a server that has been provisioned with the Prospero feature pack. An example of WildFly maven plugin is the following:

```
<plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <version>4.0.0.Beta4</version>
                <configuration>
                    <feature-packs>
<!--                        <feature-pack>-->
<!--                            <location>org.wildfly:wildfly-galleon-pack:27.0.0.Final-SNAPSHOT</location>-->
<!--                        </feature-pack>-->
<!--                        <feature-pack>-->
<!--                            <location>org.wildfly.prospero:prospero-standalone-galleon-pack:1.0.0.Beta1-SNAPSHOT</location>-->
<!--                        </feature-pack>-->
                        <feature-pack>
                            <location>org.wildfly.prospero:prospero-wildfly-galleon-pack:1.0.0.Beta1-SNAPSHOT</location>
                        </feature-pack>
                    </feature-packs>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

What I am missing in this scenario?

**Comment by spyrkob** [comment]
@yersan how did you provision the server in first place? Using `prospero install` ?

**Comment by spyrkob** [comment]
AFAIK the wildfly-maven-plugin doesn't install the metadata needed by prospero (`.installation/manifest.yaml` and `.installation/installer-config.yaml`)

**Comment by spyrkob** [comment]
@jfdenise do you think we could/should add option in the wildfly-maven-plugin to generate the .installation/manifest.yaml?

**Comment by yersan** [comment]
Having something like this or even better by using the wildfly-galleon-plugin will help for preparing server distributions (with prospero) that can be used in the testsuite.

**Comment by jfdenise** [comment]
@spyrkob , we could generate the .installation/manifest.yaml, we are currently generating a target/server/.channels.yaml file that is actually the manifest.yaml. Would that be enough? Other files generated by prospero and located in .installation/ are also strongly required to be able to update an installation?

**Comment by spyrkob** [comment]
@jfdenise we also need `.galleon/provision[ed|ing].xml` (that's already generated). We need the `.installation/installation-config.xml` with the list of channels used to install/update the server, but we can generate and add it to the server afterwards if we don't have that information at plugin runtime

**Comment by jfdenise** [comment]
@spyrkob , there is also .installation/channels.yaml file. We should have the wildfly-channel library to help generate the manifest.yaml and channels.yaml. This PR should expose an API to generate these 2 correct? https://github.com/wildfly-extras/wildfly-channel/pull/109

**Comment by yersan** [comment]
From my naive point of view, `.installation/installation-config.xml` should be able to be generated with the wildfly-maven-plugin feature packs in use.

This installation configuration should be composed of one manifest per feature pack used in the plugin. The manifest:url of each `.installation/installation-config.xml` manifest entry should point out to the Feature Pack artifact manifest generated by the wildfly-maven-plugin. By default, we can use maven central as the manifest repository.

**Comment by spyrkob** [comment]
@jfdenise `.installation/channels.yaml` has been renamed to `.installation/installation-config.yaml`

Yes, with https://github.com/wildfly-extras/wildfly-channel/pull/109 it should be possible to generate both files.

**Comment by spyrkob** [comment]
@jfdenise would it make sense to create a small prospero lib to write that data into correct place?

**Comment by jfdenise** [comment]
@spyrkob , yes, the channel lib should allow to retrieve the content, and the prospero lib would allow to store in the right place into the provisioned installation.

**Comment by spyrkob** [comment]
@yersan I think this should be resolved in https://issues.redhat.com/browse/WFMP-177. OK to close this?

**Comment by yersan** [comment]
Sure, [WFMP-177](https://issues.redhat.com/browse/WFMP-177)should resolve this.
