### ISSUE TITLE
Add export/import operation to CLI

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#187]
Expose `InstallationExportAction#export` and `InstallationRestoreAction#restore` via CLi operation `prospero clone export --dir=server --path=output.zip` `prospero clone import --dir=server --path=output.zip`

The `import` operation should support maven parameters as well:
- --repositories
- --ofline
- --local-cache
- --no-resolve-local-cache

**Comment by gaol** [comment]
should we close it with #202 merged ?

**Comment by spyrkob** [comment]
@gaol I'm marking the issues resolved on `future` branch with the `future_branch` label and will resolve them all when I can merge them into `main`
