### ISSUE TITLE
Rename installer-config.yaml to installer-channels.yaml

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#188]
The installer-channels.yaml should contain channels the installation is subscribed to. 
The installer-config.yaml might be used in future for Prospero specific configurations.

**Comment by TomasHofman** [comment]
I'm going to take a look at this.

**Comment by TomasHofman** [comment]
But in that case it would perhaps be better to wait after https://github.com/wildfly-extras/prospero/pull/198 is merged, or rebase it on top of that, if it looks we want to keep that one. It starts to snowball...

**Comment by spyrkob** [comment]
> I will also try to rename the ProsperoConfig class to ChannelsConfig.
I think I'd rather leave that as ProsperoConfig. In future we might want to add some additional configs outside of channels
