### ISSUE TITLE
Introduce command that would list available profiles

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#204]
Maybe `list-predefined-names` as a working name. This can also be an opportunity to reconsider what these "pre-defined names" should be officially called.

**Comment by TomasHofman** [comment]
@spyrkob is this OK with you?

**Comment by spyrkob** [comment]
Ideally that would be something autocompletion can provide. The available options are already listed in the help message by the way.

Maybe instead of a separate operation that could be additional text in `install` help message?

**Comment by spyrkob** [comment]
@TomasHofman do you think the autocompletion solves this or does this need more changes?

**Comment by TomasHofman** [comment]
My preference would be to have a command, because not everybody uses completion, and it's extra work to set it up. But it's not a blocker, we could also review this after Beta, when we have more feedback.

**Comment by spyrkob** [comment]
Thinking about naming - `install list-profiles` makes more sense to me, but it would mean adding a subcommand to install while maintaining existing usage. Maybe adding a parameter `install --list-profiles` that would ignore all other parameters and just print the values?

**Comment by TomasHofman** [comment]
My preferences would be `list-profiles` or `install --list-profiles` :).

**Comment by spyrkob** [comment]
Let's go with `install --list-profiles`.

Requirements:
- Add `--list-profiles` parameter to the `install command`
- The `--list-profiles` parameter should be exclusive with `--profile`, `--definition` or `--fpl` parameters
- When `install --list-profiles` is executed the user should see a message listing available profiles including:
  - the feature packs that will be installed (note we don't need to include additional information like added packages, etc)
  - channel(s) information
    - manifest location
    - repositories used


Possible future work 
- consider if we can restructure `install` command to have sub-commands something like `install list-profiles`, `install profile`, `install feature-pack`, `install print-license`.

**Comment by parsharma** [comment]
Is anyone working on this issue?
Thanks

**Comment by spyrkob** [comment]
I assigned it to you @parsharma
