### ISSUE TITLE
Update the `channel add` command to accept channel as well as manifest

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#206]
The `install` command is accepting manifest or channels. The `channel add` command should offer the same options.

**Comment by TomasHofman** [comment]
Hello @parsharma, I think this issue is still relevant.

With the `install` command we have these two options:

```
# reference a channel:
./prospero install --fpl org.wildfly.core:wildfly-core-galleon-pack::zip --dir wfcore --channels examples/wildfly-core-channel.yaml

# or reference a manifest and repos:
./prospero install --fpl org.wildfly.core:wildfly-core-galleon-pack::zip --dir wfcore2 --manifest examples/wildfly-core-manifest.yaml --repositories central::https://repo1.maven.org/maven2/
```

With the `channel add` command, we can only reference manifest and repositories:

```
./prospero channel add --channel-name channel-1 --manifest examples/wildfly-core-manifest.yaml --repositories central::https://repo1.maven.org/maven2/ --dir wfcore2
```

but we could also have the option to reference just channel, just like in the `install` command.

Do you have any objections @spyrkob ?

**Comment by spyrkob** [comment]
Sounds good. A couple comments:

- the `--channel` should be mutually exclusive with `--manifest` and `--repositories`
- the YAML file can contain multiple channels - I suppose to be consistent with `install` all should be added
- all the added channels have to have a name present. That has to be validated before any of the channels are added
