### ISSUE TITLE
Make --update-dir optional when using --dry-run for "update prepare" 

### ISSUE THREAD

**Issue by yersan** [wildfly-extras/prospero#226]
At this moment, --update-dir is mandatory even when I'm using dry-run.

update prepare --dry-run --dir=... should be enough for getting a list of available updates.

**Comment by spyrkob** [comment]
Actually thinking about it, maybe the best way would be to remove --dry-run and replace it with update list or update check subcommand WDYT?

**Comment by yersan** [comment]
`update list` makes sense to me too.

**Comment by yersan** [comment]
If you slipt it up, then there will be a time gap between the `update list `and `update prepare`, so your list could end up preparing different updates

**Comment by yersan** [comment]
well, we always get such a possibility, I don't know if the tool is doing something behind scenes to prevent preparing a different server that has been updated with a different set of updates.

If you slipt them up, you will also remove the user configuration accepting the list of updates?

**Comment by spyrkob** [comment]
> well, we always get such a possibility, I don't know if the tool is doing something behind scenes to prevent preparing a different server that has been updated with a different set of updates.

no there's no check at the moment. We could add it though if it's necessary 

> If you split them up, you will also remove the confirmation to accept the list of updates?

no, the confirmation will still be there as well as the `--yes` override
