### ISSUE TITLE
Support updating existing server installation (installed from ZIP)

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#255]
Use product name (eg. wildfly) and version (eg. 27.0.0.Final) to generate `.galleon/provisioned.xml`, `.installation/manifest.yaml` and default `.installation/installer-channels.yaml`

**Comment by gaol** [comment]
> Use product name (eg. wildfly) and version (eg. 27.0.0.Final) 

If we want to generate these metadata files from a vanilla installation, what are product name and version used for ?

**Comment by spyrkob** [comment]
They're needed to establish the GAV of the manifest file from which the versions would be pulled and the feature pack to use in galleon configuration.
