### ISSUE TITLE
Manifest is a mandatory argument  to subscribe the installation to a new channel

### ISSUE THREAD

**Issue by yersan** [wildfly-extras/prospero#273]
It should be able to subscript to a channel without specifying a manifest, at the moment I'm getting the following error when I try to do it:

```
prospero.sh channel add --dir=/tmp/wildfly-prospero --channel-name=test --repositories=/something
Missing required option: '--manifest=<gavUrlOrPath>'
```

**Comment by spyrkob** [comment]
I think for the CLI usage it's OK to expect the manifest present. The manifest would not be used only in open channels which are more advanced feature IMO

**Comment by yersan** [comment]
In such a case, I'll add the same restriction at the Mgmt Operation level
