### ISSUE TITLE
Can't make the `revert` command running correctly.

### ISSUE THREAD

**Issue by liweinan** [wildfly-extras/prospero#283]
I have a provisioned WildFly installation with two histories:

```bash
➤ ./prospero history --dir=wfly-27                                                                                                     23:11:56
[b5d2ed78] 2023-02-21T15:07:47Z - update
[3a9c0837] 2023-02-12T17:22:06Z - install
```

I tried to do the `revert` but failed:

```bash
➤ ./prospero revert perform --dir=wfly-27 --revision=3a9c0837
Feature-packs resolved.


ERROR: The following plugin options are not recognized: jboss-reset-embedded-system-properties
```

I run the above command in a locally built and installed `prospero`.

**Comment by spyrkob** [comment]
@liweinan what was the manifest you used to install wildfly originally? It looks like the version of galleon-plugins artifact in the first installation is too old. We had to update to a 6.3.0 version recently which broke backwards compatibility

**Comment by liweinan** [comment]
> @liweinan what was the manifest you used to install wildfly originally? It looks like the version of galleon-plugins artifact in the first installation is too old. We had to update to a 6.3.0 version recently which broke backwards compatibility

The manifest I used is:

```bash
➤ ./prospero install --fpl=wildfly --dir=wfly-27-test --channel=examples/wildfly-27.0.0.Alpha2-channel.yaml
```

I fetched and rebased my `prospero` main branch into newest and rebuild the project, then I delete the WildFly dir and regenerate it, then I did a revert it works:

```bash
➤ ./prospero revert perform --dir=wfly-27-test --revision=452d0d17                                                                     23:51:08
Feature-packs resolved.
Packages installed. 100%
JBoss modules installed. 100%
Configurations generated.
Updates found:
  [*]io.undertow:undertow-core                             2.2.18.Final         ==>  2.2.17.Final

[*] The update list contain one or more artifacts with lower versions then currently installed. Proceed with caution.

Continue with update [y/N]: y

weli@192:~/w/prospero|main⚡*?
➤ ./prospero history --dir=wfly-27-test                                                                                                23:51:53
[6c0318d8] 2023-02-21T15:51:51Z - rollback
[289c9776] 2023-02-21T15:50:09Z - update
[452d0d17] 2023-02-21T15:47:44Z - install
```

So the problem is fixed :D

Thanks!
