### ISSUE TITLE
Add help and syntax description

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#33]
Add help operation listing available operations and their parameters.

Add --help argument to operations to display the operation's parameter

**Comment by TomasHofman** [comment]
Hi @spyrkob , I wanted to look at this as the "usage" information are big help for anybody who would want to test prospero at this point, me included.

I noticed you use a self cooked implementation of CLI interface. Are you opposed to using some ready made library?

As an example I created a [draft that uses the picocli library](https://github.com/spyrkob/prospero/pull/55) (which is used by Quarkus to build their CLI tools) just as an example to consider. The benefit is that "usage" outputs are automatically generated, and they are nicely formatted too. Take a look.

![Screenshot from 2022-06-17 12-32-19](https://user-images.githubusercontent.com/353221/174281561-ca16a03c-23ff-4600-a655-7a25b50fa3ee.png)

**Comment by spyrkob** [comment]
Hey, I was going to look into CLI libraries as part of this issue, picocli looks good, if Quarkus is using it as well, I'm happy with it

**Comment by TomasHofman** [comment]
You can assign this issue to me then :).

**Comment by spyrkob** [comment]
Thanks!
