### ISSUE TITLE
Known profile doesn't reference a manifest error

### ISSUE THREAD

**Issue by honza-kasik** [wildfly-extras/prospero#380]
Known profile defined in [prospero-known-combinations.yaml](https://github.com/wildfly-extras/prospero/blob/main/prospero-common/src/main/resources/prospero-known-combinations.yaml) has `manfest: null`. Trying to install this profile with Beta11 ends up with an error:

```bash
> ./prospero/bin/prospero.sh install --dir=foobar --profile=wildfly
ERROR: PRSP000207: Invalid channel: Channel 'wildfly' doesn't reference a manifest.
Add required channels using [--manifest] argument.
```

This applies for both Beta11 and Final revisions.

**Comment by spyrkob** [comment]
@honza-kasik that's expected behaviour as the wildfly manifest is not published atm. There is an example manifest in examples directory that can be used with `--manifest=examples/wildfly-27.0.0.Alpha2-manifest.yaml`

**Comment by spyrkob** [comment]
Update the configuration to use `org.wildfly.channels:wildfly` manifest in Central repository when WildFly 32.0.0.Final is published
