### ISSUE TITLE
CLIProvider does not supply a command for PowerShell scripts

### ISSUE THREAD

**Issue by yersan** [wildfly-extras/prospero#388]
It seems CliProviderImpl is unable to detect whether we are running on PowerShell and only supply the .sh and bat variants.

See:

https://github.com/wildfly-extras/prospero/blob/7256b85a074f963df6a1c9593ec6258616aabb3b/prospero-cli/src/main/java/org/wildfly/prospero/cli/spi/CliProviderImpl.java#L35C1-L38

**Comment by spyrkob** [comment]
Fixed by https://github.com/wildfly-extras/prospero/pull/389
