### ISSUE TITLE
Add management operations to list, add and remove maven repositories and channels

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#41]
Add operations to manipulate configured repositories and channels

Example operations:
`prospero repositories list`
`prospero repositories add central https://repo1.maven.org/maven2/`
`prospero repositories remove central`

`prospero channels list`
`prospero repositories add https://localhost/channel.yaml`
`prospero repositories remove https://localhost/channel.yaml`

**Comment by TomasHofman** [comment]
I can take a look at this.

**Comment by spyrkob** [comment]
Just FYI I'm working on #42 now, I'll need to add the API to manipulate the config there, so we'll need to sync up on this
