### ISSUE TITLE
When displaying the update candidates, display the name of the channel the update was found in

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#411]
The example output would be:

```
Updates found:
  org.yaml:snakeyaml                                    1.29                 ==>  1.33  [EAP 8.0]
```

Note: `ChannelSession` in wildfly-channel will have to be modified to expose this information.
Note2: The update candidate would have to preserve this information to display diff correctly.

**Comment by moulalis** [comment]
Hi @spyrkob could you please assign this to me?
