### ISSUE TITLE
Allow selectively loading common.conf.bat when launching Prospero

### ISSUE THREAD

**Issue by yersan** [wildfly-extras/prospero#465]
When the Prospero distribution (prospero.bat) is invoked it tries to load environment variables configuration by invoking `:commonConf` label loaded from `common.bat` file, which in turn loads any configuration variable under common.conf.bat.

When we are installing from the server environment, loading `common.conf.bat` should not be necessary, since the server common.conf.bat environment should have been loaded successfully when the server was launched.

Ideally, we should be able to disable loading the `common.conf.bat` under request to prevent loading `common.conf.bat` twice could having side effects when prospero.bat is being invoked. An argument to prospero.bat could be enough.

In any case, loading `common.conf.bat` has no effect on the original server environment since the original environment is restored once prospero.bat finishes.

A different solution could be to avoid the loading of `common.conf.bat`  if it has been already loaded and approach this on the server bits, but that sounds like a more dirty solution.

**Comment by spyrkob** [comment]
@yersan thanks. I assume the same applies to linux script as well?

**Comment by yersan** [comment]
Hi @spyrkob , yes, since `prospero.sh` invokes it, that invocation is unnecessary when `prospero.sh` is invoked from `standalone.sh`

Note: I have not found in Prospero if `common.conf.ps1` is somehow invoked, but if it is, we could also avoid loading it again

**Comment by yersan** [comment]
To be more clear, since it seems a bit convoluted my description:

prospero.sh invokes common.sh which will invoke common.conf
prospero.bat invokes common.bat which will invoke common.conf.bat

When we are launching prospero.sh / prospero.bat from the server, we do not need to invoke again common.sh/common.bat. It looks harmless, but unnecessary.

**Comment by yersan** [comment]
ahh, right, they are sourced in standalone.sh but not exported, so they are not visible when they are invoked in a new script. Windows looks different then.
