### ISSUE TITLE
Provide a CliMain variant that doesn't call System.exit

### ISSUE THREAD

**Issue by bstansberry** [wildfly-extras/prospero#515]
Using the Prospero CLI as part of a maven build (e.g. with the exec-maven-plugin) doesn't work because CliMain calls System.exit. Provide a variant, e.g. CliMainNoExit, that doesn't call System.exit.

CliMain actually exposes createCommandLine as a public method so it's simple enough for other projects to create such a class, which is what I'm doing in WF to work around this. But that requires some hackiness in the WF build.

**Comment by spyrkob** [comment]
Just to confirm - does that apply to error scenarios as well or just the successful execution?

**Comment by bstansberry** [comment]
BTW, that class is way too complicated; it includes useless stuff I forgot to remove after adding config like https://github.com/wildfly/wildfly/pull/17470/files#diff-ab7939563ab2ed2a32ec4f069f5755fe052e9555777de64f3c0dbe8489bbdde3R495

That said, there is something happening with CliMain where a couple daemon threads don't stop, which results in needing that exec-maven-plugin section. I'll try to recreate and post details.
