### ISSUE TITLE
Allow execution of the jboss-eap-installation-manager.sh from inside of the `bin/` directory

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#587]
```
$ ./jboss-eap-installation-manager.sh update list
ERROR: Path `/home/thofman/prospero/eap-8/bin/.` does not contain a server installation provisioned by the jboss-eap-installation-manager.
  Maybe you forgot to specify path to the installation (--dir)?
  Server installation needs to contain a `.galleon` folder and an `.installation/installer-channels.yaml` file.
```

It would be nice to be able to execute prospero directly from the `bin/` directory, because that's what I'm used to do :).

Maybe looking recursively into parent directories for the `.installation/` directory? Or just looking into the immediate parent dir if `.installation/` is not in the current dir?

**Comment by spyrkob** [comment]
@TomasHofman I understand this applies when using prospero embedded inside Wildfly server right? If that's the case maybe we can change the script in the `wildfly-prospero-galleon-pack` itself to set the --dir to JBOSS_HOME?

**Comment by TomasHofman** [comment]
@spyrkob I think that could work, if user is still able to override `--dir` by specifying it in his invocation...

**Comment by spyrkob** [comment]
yeah that should be possible, if the argument is present the script wouldn't change it

**Comment by spyrkob** [comment]
Looking at this again, the `prospero.sh|bat|ps1` script is shared between standalone and wildfly FPs, so I think it's better to make this change in `AbstractCommand#determineInstallationDirectory`.
I believe we can recursively check all parents until we find first folder with `.galleon`/.`.installation` subfolders, then validate it as currently.

**Comment by parsharma** [comment]
I would like to work on this issue. Thanks
