### ISSUE TITLE
Input validation - decline to provision into a non-empty directory?

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#59]
If I run `prospero install --dir=eap ...` and the `eap/` directory is non-empty (e.g. contains an old server instance), should prospero report an error, as a safety measure?

**Comment by TomasHofman** [comment]
It currently appears to perform an update, according to `history` command, although the command that was run was `install` in both cases:

```
[thofman@rama prospero]$ java -jar prospero-cli/target/prospero-cli-1.0-SNAPSHOT-shaded.jar history --dir wf-core
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[be5d0121] 2022-06-22T09:08:12Z - update
[524f1f3b] 2022-06-22T09:06:17Z - install
```

**Comment by spyrkob** [comment]
Yes this should be an error.

**Comment by TomasHofman** [comment]
I'm going to open a PR for this.
