### ISSUE TITLE
Publish Prospero documentation on https://docs.wildfly.org

### ISSUE THREAD

**Issue by jmesnil** [wildfly-extras/prospero#687]
To publish Prospero docs on https://docs.wildfly.org, we would need:

* Automatically generate docs whenever we do a release of Prospero
  * -> The [prospero-build-1.2.3.Final.zip](https://github.com/wildfly-extras/prospero/releases/download/1.2.3.Final/prospero-build-1.2.3.Final.zip) contains an empty `docs` dir. This looks to be a bug as I was expected to get the generated content from https://github.com/wildfly-extras/prospero/tree/main/dist/docs 
* Open a PR in https://github.com/wildfly/wildfly.github.io that would add this doc in a `prospero` subdirectory
  * -> this would make the doc available at https://docs.wildfly.org/prospero

**Comment by spyrkob** [comment]
@jmesnil thanks, I'll take a look at the first point. 

As to the publication - does it mean that's a manual process to update the documentation, i.e. every time new version has to be pushed to [wildfly/wildfly.github.io](https://github.com/wildfly/wildfly.github.io)?

**Comment by jmesnil** [comment]
yes, whenever you release, you'd have to update https://github.com/wildfly/wildfly.github.io and merge the updated doc.
