### ISSUE TITLE
Use jackson-databind library in WildFly modules in the WildFly feature pack

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#704]
Instead of adding the jackson-databind to prospero-dep module, use `com.fasterxml.jackson.dataformat.jackson-dataformat-yaml` wildfly-ee module.

**Comment by parsharma** [comment]
@spyrkob can I take it?

**Comment by spyrkob** [comment]
@parsharma  sure

**Comment by TomasHofman** [comment]
@spyrkob , how would standalone prospero installation inherit the the module from wildfly-ee?

**Comment by TomasHofman** [comment]
Aha - there are two prospero-dep modules, so this would only be done in the wildfly-galleon-pack module?

**Comment by TomasHofman** [comment]
The com.fasterxml.jackson.dataformat.jackson-dataformat-yaml is only available in XP5, isn't that a problem?
