### ISSUE TITLE
Fix slf4j warning when running from jboss-modules

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#72]
When using prospero provisioned as standalone FP, SLF4J warning is issued:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
In shaded jar this is fixed by adding slf4j-nop library

**Comment by TomasHofman** [comment]
I can take a look if you are not in it already.

**Comment by spyrkob** [comment]
Sure. I suspect it might be because other slf4j jars are in a different module, but hasn't tried it yet
