### ISSUE TITLE
The `--manifest` parameter doesn't accept list of coordinates

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#726]
The `--channel` parameter accepts list of coordinates, which is very practical. The `--manifest` parameter should support it too.

**Comment by spyrkob** [comment]
It's possible to add this to the `install` operation, that would result in creation of multiple channels with the same repositories.
I think it would not be possible in the `channel add` operation though since that operation requires `--channel-name` and creates a single channel
