### ISSUE TITLE
Make predefined FPLs visible to the user

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#78]
User should have a way to list predefined FPLs ("eap", "eap-8.0", ...). Maybe they should use a different CLI option than the "custom" FPLs in the install command?

**Comment by TomasHofman** [comment]
Good idea. I'm not sure if I can make the help string dynamically generated though.

There is also the [ticket](https://github.com/wildfly-extras/prospero/issues/40) about allowing arbitrary versions (e.g. "eap-8.0.1"). Is that use case also intended to use the same predefined configuration (packages, repositories) as "eap"?

**Comment by spyrkob** [comment]
Maybe just hardcoded is enough for now as we're only going to support EAP and XP initially (and possibly Wildfly).

As for #40 - thinking about it, I'm not sure if it actually makes sense as the channels would override the exact version. Maybe that needs to be limited to major.minor version which would be used to select channel G:A

**Comment by TomasHofman** [comment]
So XP can be just "xp", or do you want to append some version to it? I'm not sure if it's XP 5 or 6.

Re #40, I guess it's better to just stick to hardcoded "eap-80", and in future add "eap-81". Eventually to add dots.

When providing "fully qualified" fpl, do we expect just G:A, like "org.jboss.eap:wildfly-ee-galleon-pack"? Or at least is that what should be in the usage message? The version is gonna be determined from channel?

**Comment by spyrkob** [comment]
> When providing "fully qualified" fpl, do we expect just G:A, like "org.jboss.eap:wildfly-ee-galleon-pack"? Or at least is that what should be in the usage message? The version is gonna be determined from channel?
Yes. The channel will dictate feature pack's version
>So XP can be just "xp", or do you want to append some version to it? I'm not sure if it's XP 5 or 6.
"xp" should resolve to latest known major version, apart from that we should have "xp-50" to XP5, "xp-60" to XP6 etc
