### ISSUE TITLE
Should the temporary provisioning repos be deleted?

### ISSUE THREAD

**Issue by TomasHofman** [wildfly-extras/prospero#81]
I found quite a few repositories in my `/tmp` folder, like `/tmp/provisioning-repo7585379810969367448/`. Are they needed for anything after a server was installed? Should the tool remove them after provisioning is complete?

**Comment by spyrkob** [comment]
They should be removed. IIRC they should be already marked with `deleteOnExit()`, but I guess we can add `MavenSessionManager#close()` to make sure it's removed
