### ISSUE TITLE
Warn user if any conflicts detected

### ISSUE THREAD

**Issue by spyrkob** [wildfly-extras/prospero#88]
Probably will need to modify Galleon for this.

Example: if user modified file 'standalone.xml' and the update modified 'standalone.xml', before the old server is replaced with updated one, we should prompt user whether he's happy to continue.

**Comment by spyrkob** [comment]
Galleon issue: https://issues.redhat.com/browse/GAL-338

**Comment by jfdenise** [comment]
With the redesign of the update (WIP branch: https://github.com/jfdenise/prospero/tree/future), such logic should be implemented directly in Prospero.
