### ISSUE TITLE
Clarify usage of Maven configuration

### ISSUE THREAD

**Issue by jmesnil** [wildfly-extras/prospero#94]
I find the usage of the Maven configuration ambiguous:

```
./prospero install --help
Install a new application server instance.

      --channel=<channel>   Channel file URL.
      --channel-repo=<channelRepositories>
                            URL of a remote Maven repository that contains artifacts required to build an application container.
```
-> I find the name `channel-repo` confusing. aiui, this parameter allows to configure any Maven repositories to fetch the application server bits. Could it be renamed to `remote-repositories` ? 
-> The help message should be updated to something like: `URLs of remote Maven repositories that contains the artifacts required to install the application server ( multiple URLs are separated by comma).

```
      --local-repo=<localRepo>
                            Path to a local Maven repository.
```
-> should be path to *the* local Maven repository (there is always a single local maven repo). 
-> could it default to $HOME/.m2/repository?

```
      --offline             Perform installation from local Maven repository only. Offline installation requires --local-repo to be configured.
```
-> if we provide a default value for local-repo, offline installation would not required it to be configured. wdyt?

If I want to perform an offline installation, ideally, I should be able to run

```
 ./prospero install --fpl=eap-8.0 --dir=eap8 --channel-repo=file:///Users/jmesnil/tmp/jboss-eap-8.0.0.Beta-maven-repository/maven-repository/ --offline
```

**Comment by jmesnil** [comment]
https://github.com/wildfly-extras/prospero/blob/8b3aab3446b1925fb9d93ebbc93158e9675ddff4/prospero-cli/src/main/java/org/wildfly/prospero/cli/commands/InstallCommand.java#L116

Only the first URL from `channel-repo` is used, is that correct?

**Comment by spyrkob** [comment]
> Only the first URL from channel-repo is used, is that correct?
That seems to be a mistake from when we moved to Picocli. I'll fix that

**Comment by jmesnil** [comment]
>Or maybe using ~/.m2/repository should be default, --local-repo allows to change this location and a new flag (eg --no-local-repo) would use the temp?

That sounds a good approach. `--no-local-repo` could be renamed to `--no-resolve-local-cache` or something similar?

**Comment by spyrkob** [comment]
cc @marekkopecky
